"use client";

import type { CSSProperties } from "react";
import { Mail, Phone, MapPin, Linkedin, Globe2 } from "lucide-react";
import { cvTemplates } from "./constants";
import type { CvFormData } from "./types";

export function CvPreview({ data }: { data: CvFormData }) {
  const template = cvTemplates.find((item) => item.id === data.templateId) ?? cvTemplates[0];
  const hasContent = data.fullName || data.roleTitle || data.summary || data.experiences.length || data.education.length || data.skills.length;
  const contact = [{ icon: Mail, value: data.email }, { icon: Phone, value: data.phone }, { icon: MapPin, value: data.address }, { icon: Linkedin, value: data.linkedin }].filter((item) => item.value);
  return <div className="cv-paper" style={{ "--cv-accent": template.color } as CSSProperties}>
    <div className="cv-paper-header"><div><p className="cv-paper-kicker">HIREAI / CANDIDATE PROFILE</p><h1>{data.fullName || "Họ và tên của bạn"}</h1><p className="cv-paper-role">{data.roleTitle || "Vị trí ứng tuyển"}</p></div><div className="cv-paper-mark">CV<br /><span>26</span></div></div>
    <div className="cv-paper-body"><aside className="cv-paper-sidebar"><div className="cv-sidebar-block"><p className="cv-paper-label">LIÊN HỆ</p>{contact.length ? contact.map(({ icon: Icon, value }) => <p className="cv-contact" key={value}><Icon className="h-3.5 w-3.5" />{value}</p>) : <p className="cv-placeholder">Email, số điện thoại và liên kết sẽ xuất hiện ở đây.</p>}</div><div className="cv-sidebar-block"><p className="cv-paper-label">KỸ NĂNG</p>{data.skills.length ? <div className="cv-skill-list">{data.skills.map((skill) => <span key={skill}>{skill}</span>)}</div> : <p className="cv-placeholder">Thêm kỹ năng nổi bật của bạn.</p>}</div><div className="cv-sidebar-block"><p className="cv-paper-label">NGÔN NGỮ</p><p className="cv-language">Tiếng Việt <span>Bản ngữ</span></p><p className="cv-language">English <span>Professional</span></p></div></aside><div className="cv-paper-main">{data.summary ? <section className="cv-paper-section"><p className="cv-paper-label">TÓM TẮT</p><p className="cv-paper-text">{data.summary}</p></section> : <section className="cv-paper-section cv-paper-empty"><p className="cv-paper-label">TÓM TẮT</p><p className="cv-placeholder">Viết vài dòng về kinh nghiệm, thế mạnh và điều bạn muốn tạo ra.</p></section>}{data.experiences.length ? <section className="cv-paper-section"><p className="cv-paper-label">KINH NGHIỆM</p>{data.experiences.map((exp) => <div className="cv-paper-entry" key={exp.id}><div className="cv-entry-heading"><div><h3>{exp.position || "Vị trí công việc"}</h3><p>{exp.company || "Tên công ty"}</p></div><span>{exp.duration || "Thời gian"}</span></div>{exp.description && <p className="cv-paper-text cv-entry-description">{exp.description}</p>}</div>)}</section> : <section className="cv-paper-section cv-paper-empty"><p className="cv-paper-label">KINH NGHIỆM</p><p className="cv-placeholder">Các vai trò và thành tựu của bạn sẽ được cập nhật realtime.</p></section>}{data.education.length > 0 && <section className="cv-paper-section"><p className="cv-paper-label">HỌC VẤN</p>{data.education.map((edu) => <div className="cv-paper-entry" key={edu.id}><div className="cv-entry-heading"><div><h3>{edu.degree || "Chuyên ngành"}</h3><p>{edu.school || "Trường / Học viện"}</p></div><span>{edu.year}</span></div></div>)}</section>} {!hasContent && <div className="cv-paper-welcome"><Globe2 className="h-8 w-8" /><p>Bắt đầu điền để tạo nên câu chuyện nghề nghiệp của bạn.</p></div>}</div></div>
  </div>;
}
