import type { Job } from "./types";

export const mockJobs: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "NEXORA Technologies",
    logo: "NX",
    salary: "25 - 40 triệu",
    location: "Hà Nội",
    level: "Senior",
    employmentType: "Full-time",
    skills: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    postedAt: "2 ngày trước",
    description: "Tìm Senior Frontend Developer có kinh nghiệm với React ecosystem. làm việc với sản phẩm SaaS B2B, team 8 người.",
    applicants: 24,
    isHot: true,
  },
  {
    id: "2",
    title: "Backend Engineer (Node.js)",
    company: "CLOUDLY Infrastructure",
    logo: "CL",
    salary: "20 - 35 triệu",
    location: "Hồ Chí Minh",
    level: "Mid",
    employmentType: "Full-time",
    skills: ["Node.js", "PostgreSQL", "Docker", "AWS"],
    postedAt: "1 ngày trước",
    description: "Phát triển microservices cho nền tảng cloud. Yêu cầu kinh nghiệm 2+ năm với Node.js và SQL.",
    applicants: 18,
    isHot: true,
  },
  {
    id: "3",
    title: "Junior React Developer",
    company: "PIXELFORGE Studio",
    logo: "PF",
    salary: "12 - 18 triệu",
    location: "Đà Nẵng",
    level: "Junior",
    employmentType: "Full-time",
    skills: ["React", "JavaScript", "CSS", "Git"],
    postedAt: "3 ngày trước",
    description: "Cơ hội cho Fresher/Junior Developer muốn phát triển frontend. Có mentor hỗ trợ.",
    applicants: 42,
    isHot: false,
  },
  {
    id: "4",
    title: "Data Analyst Intern",
    company: "DATANEST AI",
    logo: "DN",
    salary: "5 - 8 triệu",
    location: "Hà Nội",
    level: "Intern",
    employmentType: "Part-time",
    skills: ["Python", "SQL", "Excel", "Power BI"],
    postedAt: "5 ngày trước",
    description: "Thực tập sinh phân tích dữ liệu, hỗ trợ team BI. Ưu tiên sinh viên năm 3,4.",
    applicants: 67,
    isHot: false,
  },
  {
    id: "5",
    title: "DevOps Engineer",
    company: "CLOUDLY Infrastructure",
    logo: "CL",
    salary: "30 - 50 triệu",
    location: "Remote",
    level: "Senior",
    employmentType: "Full-time",
    skills: ["Kubernetes", "Terraform", "CI/CD", "Azure"],
    postedAt: "1 ngày trước",
    description: "Quản lý hạ tầng cloud, triển khai CI/CD pipeline. Kinh nghiệm 4+ năm.",
    applicants: 12,
    isHot: true,
  },
  {
    id: "6",
    title: "UI/UX Designer",
    company: "PIXELFORGE Studio",
    logo: "PF",
    salary: "15 - 25 triệu",
    location: "Hồ Chí Minh",
    level: "Mid",
    employmentType: "Full-time",
    skills: ["Figma", "Design System", "Prototyping", "User Research"],
    postedAt: "4 ngày trước",
    description: "Thiết kế giao diện sản phẩm số. Yêu cầu portfoliostrong.",
    applicants: 31,
    isHot: false,
  },
  {
    id: "7",
    title: "Python Backend Developer",
    company: "NEXORA Technologies",
    logo: "NX",
    salary: "22 - 38 triệu",
    location: "Hà Nội",
    level: "Mid",
    employmentType: "Full-time",
    skills: ["Python", "Django", "FastAPI", "Redis"],
    postedAt: "2 ngày trước",
    description: "Phát triển API backend cho hệ thống SaaS.成為-)",
    applicants: 15,
    isHot: false,
  },
  {
    id: "8",
    title: "Mobile Developer (Flutter)",
    company: "DATANEST AI",
    logo: "DN",
    salary: "18 - 30 triệu",
    location: "Remote",
    level: "Junior",
    employmentType: "Full-time",
    skills: ["Flutter", "Dart", "Firebase", "REST API"],
    postedAt: "6 ngày trước",
    description: "Phát triển ứng dụng mobile cross-platform. Có kinh nghiệm Flutter là plus.",
    applicants: 28,
    isHot: false,
  },
  {
    id: "9",
    title: "QA Engineer",
    company: "CLOUDLY Infrastructure",
    logo: "CL",
    salary: "15 - 25 triệu",
    location: "Hồ Chí Minh",
    level: "Mid",
    employmentType: "Full-time",
    skills: ["Manual Testing", "Selenium", "JIRA", "API Testing"],
    postedAt: "3 ngày trước",
    description: "Kiểm thử phần mềm, viết test case, automate testing pipeline.",
    applicants: 22,
    isHot: false,
  },
  {
    id: "10",
    title: "AI/ML Engineer",
    company: "DATANEST AI",
    logo: "DN",
    salary: "35 - 60 triệu",
    location: "Hà Nội",
    level: "Senior",
    employmentType: "Full-time",
    skills: ["Python", "TensorFlow", "PyTorch", "MLOps"],
    postedAt: "1 ngày trước",
    description: "Phát triển và deploy các mô hình AI/ML production. Yêu cầu kinh nghiệm 3+ năm.",
    applicants: 8,
    isHot: true,
  },
  {
    id: "11",
    title: "Product Manager",
    company: "NEXORA Technologies",
    logo: "NX",
    salary: "30 - 50 triệu",
    location: "Hồ Chí Minh",
    level: "Lead",
    employmentType: "Full-time",
    skills: ["Product Strategy", "Agile", "Data Analysis", "User Research"],
    postedAt: "5 ngày trước",
    description: "Quản lý sản phẩm SaaS, định hướng chiến lược và roadmap.",
    applicants: 19,
    isHot: false,
  },
  {
    id: "12",
    title: "Full-stack Developer",
    company: "PIXELFORGE Studio",
    logo: "PF",
    salary: "20 - 35 triệu",
    location: "Đà Nẵng",
    level: "Mid",
    employmentType: "Full-time",
    skills: ["React", "Node.js", "MongoDB", "TypeScript"],
    postedAt: "2 ngày trước",
    description: "Phát triển full-stack cho ứng dụng web. Làm việc với startup environment.",
    applicants: 33,
    isHot: false,
  },
];
