using Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Infrastructure.Persistence.Configurations
{
    public class CvThemeConfiguration : IEntityTypeConfiguration<CvTheme>
    {
        public void Configure(EntityTypeBuilder<CvTheme> builder)
        {
            builder.ToTable("cv_themes");
            builder.HasKey(x => x.Id);

            builder.Property(x => x.Slug).IsRequired().HasMaxLength(100);
            builder.HasIndex(x => x.Slug).IsUnique();
            builder.Property(x => x.Ten).IsRequired().HasMaxLength(255);
            builder.Property(x => x.MoTa).HasMaxLength(500);
            builder.Property(x => x.MoTaNgan).HasMaxLength(200);
            builder.Property(x => x.PreviewStorageKey).HasMaxLength(500);
            builder.Property(x => x.DanhMuc).HasMaxLength(50);
            builder.Property(x => x.NganhPhuHop).HasMaxLength(500);
            builder.Property(x => x.ViTriMucTieu).HasMaxLength(500);
            builder.Property(x => x.CapBac).HasMaxLength(50);
            builder.Property(x => x.Tags).HasMaxLength(500);
            builder.Property(x => x.PhongCachThietKe).HasMaxLength(100);
            builder.Property(x => x.MauSacChuDao).HasMaxLength(100);
            builder.Property(x => x.TamLyMauSac).HasMaxLength(500);
            builder.Property(x => x.KhuyenNghiSuDung).HasMaxLength(1000);
            builder.Property(x => x.TranhSuDungKhi).HasMaxLength(1000);
            builder.Property(x => x.GoiYAI).HasColumnType("text");
            builder.Property(x => x.EmbeddingModel).HasMaxLength(100);
            builder.Property(x => x.Embedding).HasColumnType("vector(1536)");

            var seededAt = new System.DateTime(2026, 9, 23, 0, 0, 0, System.DateTimeKind.Utc);
            CvTheme T(int id, string slug, string ten, string moTa, string moTaNgan,
                string danhMuc, string nganh, string viTri, string capBac, string tags,
                string phongCach, int soCot, bool ats, string mauSac, string tamLy,
                string khuyenNghi, string tranh, string goiYAI, bool macDinh, int thuTu, bool isActive = true)
                => new()
                {
                    Id = id, Slug = slug, Ten = ten, MoTa = moTa, MoTaNgan = moTaNgan,
                    DanhMuc = danhMuc, NganhPhuHop = nganh, ViTriMucTieu = viTri, CapBac = capBac,
                    Tags = tags, PhongCachThietKe = phongCach, SoCot = soCot, ThanThienATS = ats,
                    MauSacChuDao = mauSac, TamLyMauSac = tamLy, KhuyenNghiSuDung = khuyenNghi,
                    TranhSuDungKhi = tranh, GoiYAI = goiYAI, LaMacDinh = macDinh,
                    IsActive = isActive, ThuTu = thuTu, Created = seededAt, CreatedBy = "system"
                };

            builder.HasData(
                T(1, "minimal-ats", "Minimal ATS", "Một cột, tương thích hệ thống lọc hồ sơ",
                    "Chuẩn ATS, an toàn mọi ngành", "ats", "all", "all", "all", "ATS,Professional",
                    "ats", 1, true, "#1f2a37", "Đen than tạo cảm giác tin cậy, tập trung nội dung",
                    "Mọi ngành, đặc biệt khi nộp qua hệ thống ATS", "Portfolio sáng tạo cần ấn tượng thị giác mạnh",
                    "Mặc định an toàn khi không rõ yêu cầu nhà tuyển dụng", true, 1),
                T(2, "tech-modern", "Tech Modern", "Hai cột, dành cho IT / Developer",
                    "Chuẩn IT, sidebar kỹ năng", "developer", "IT", "Backend,Frontend,Fullstack,DevOps", "all",
                    "IT,Developer", "modern", 2, true, "#274b73", "Xanh navy truyền tải chuyên nghiệp và đáng tin",
                    "IT/Developer cần nêu bật dự án và kỹ năng", "Môi trường bảo thủ hoặc văn bản thuần túy",
                    "Đề xuất đầu tiên cho hồ sơ kỹ thuật", false, 2),
                T(3, "ats-classic", "ATS Classic", "Một cột gọn nhẹ, tối ưu hệ thống lọc hồ sơ",
                    "Gọn nhẹ, qua ATS dễ dàng", "ats", "IT", "Backend,DevOps,Data", "all",
                    "ATS,Backend,DevOps", "classic", 1, true, "#1f2a37", "Tối giản, máy đọc ưu tiên",
                    "Backend/DevOps/Data nộp qua cổng ATS", "Vai trò cần thể hiện cá tính mạnh",
                    "Bản ATS gọn hơn minimal-ats cho dân kỹ thuật", false, 3),
                T(4, "professional-split", "Professional Split", "Hai cột thanh lịch, sidebar hẹp cho IT / BA / PM",
                    "Thanh lịch 2 cột", "developer", "IT,Kinh doanh", "Backend,BA,PM", "all",
                    "IT,2 cột,Chuyên nghiệp", "modern", 2, true, "#274b73", "Navy điểm xuyết tạo chiều sâu chuyên nghiệp",
                    "IT/BA/PM cần cân bằng kỹ năng và kinh nghiệm", "Fresher ít nội dung (sidebar sẽ trống)",
                    "Khi cần 2 cột nhưng vẫn giữ vẻ trang trọng", false, 4),
                T(5, "modern-accent", "Modern Accent", "Hiện đại, điểm nhấn mạnh cho Product / Frontend",
                    "Điểm nhấn hiện đại", "developer", "IT,Sản phẩm", "Frontend,Product", "all",
                    "Hiện đại,Frontend,Product", "modern", 1, true, "#274b73", "Điểm nhấn màu dẫn mắt vào thành tựu",
                    "Product/Frontend muốn nổi bật dự án", "Hồ sơ học thuật hoặc hành chính",
                    "Cho vai trò cần năng lượng hiện đại", false, 5),
                T(6, "executive-tech", "Executive Tech", "Bố cục doanh nghiệp trang trọng cho senior / lead",
                    "Trang trọng cho lead", "senior", "IT,Quản lý", "Lead,Manager,Architect", "senior",
                    "Senior,Chuyên nghiệp,Lead", "classic", 1, true, "#1f2a37", "Trang trọng, thể hiện tầm vóc quản lý",
                    "Senior/lead ứng tuyển vị trí quản lý kỹ thuật", "Fresher/junior (quá nặng nề)",
                    "Khi cần thể hiện đẳng cấp lãnh đạo", false, 6),
                T(7, "compact-developer", "Compact Developer", "Một cột siêu gọn cho fresher / junior IT",
                    "Siêu gọn cho fresher", "developer", "IT", "Backend,Frontend,Fresher", "fresher",
                    "ATS,Fresher,Junior", "ats", 1, true, "#1f2a37", "Gọn gàng, không phô trương",
                    "Fresher/junior ít kinh nghiệm nhưng nhiều kỹ năng", "Senior có bề dày cần không gian",
                    "Tối ưu 1 trang cho người mới", false, 7, isActive: false),
                T(8, "sidebar-pro", "Sidebar Pro", "Sidebar phải, kỹ năng đặt lên đầu cho IT",
                    "Kỹ năng lên đầu", "developer", "IT", "Backend,Frontend,Fullstack", "all",
                    "IT,2 cột,Kỹ năng", "modern", 2, true, "#274b73", "Sidebar điều hướng mắt nhà tuyển dụng",
                    "IT generalist muốn khoe stack kỹ năng", "Vai trò phi kỹ thuật",
                    "Khi kỹ năng là điểm mạnh nhất", false, 8, isActive: false),
                T(9, "clean-corporate", "Clean Corporate", "Phong cách công sở chuẩn mực cho BA / PM / QA / HR",
                    "Chuẩn công sở", "corporate", "Kinh doanh,Hành chính", "BA,PM,QA,HR", "all",
                    "Corporate,BA,PM", "classic", 1, true, "#1f2a37", "Chuẩn mực, phù hợp văn hóa doanh nghiệp",
                    "BA/PM/QA/HR trong môi trường corporate", "Sáng tạo, startup (quá cứng nhắc)",
                    "An toàn cho khối văn phòng", false, 9, isActive: false),
                T(10, "creative-portfolio", "Creative Portfolio", "Cá tính mạnh, dự án dạng thẻ cho designer / frontend",
                    "Cá tính portfolio", "creative", "Thiết kế,IT", "Designer,Frontend", "all",
                    "Creative,Portfolio,Designer", "creative", 1, false, "#7a3b4d", "Đỏ burgundy khơi gợi sáng tạo và đam mê",
                    "Designer/frontend cần show dự án trực quan", "Nộp qua ATS nghiêm ngặt",
                    "Khi portfolio quan trọng hơn từ ngữ", false, 10),
                T(11, "senior-executive", "Senior Executive", "Thoáng đãng, tôn vinh kinh nghiệm lãnh đạo",
                    "Lãnh đạo thoáng đãng", "senior", "Quản lý", "Manager,Director,C-level", "senior",
                    "Senior,Leadership,Manager", "classic", 1, true, "#1f2a37", "Khoảng trắng thể hiện sự tự tin",
                    "Quản lý cấp cao với bề dày thành tích", "Người mới (thiếu nội dung sẽ lộ)",
                    "Cho hồ sơ lãnh đạo dày dặn", false, 11, isActive: false),
                T(12, "academic-cv", "Academic CV", "Học vấn lên trước, đánh số nghiên cứu / chứng chỉ",
                    "Học thuật chuẩn", "ats", "Giáo dục,Nghiên cứu", "Nghiên cứu,Học thuật", "fresher",
                    "Academic,Research,Học vấn", "ats", 1, true, "#1f2a37", "Hàn lâm, nghiêm túc",
                    "Học thuật, nghiên cứu, học bổng", "Doanh nghiệp thương mại (quá khô)",
                    "Khi học vấn là tài sản lớn nhất", false, 12),
                T(13, "data-specialist", "Data Specialist", "Dải stack nổi bật, dự án dẫn đầu cho Data / AI / ML",
                    "Chuyên Data/AI", "developer", "Data,IT", "Data,AI,ML", "all",
                    "Data,AI,ML", "modern", 1, true, "#274b73", "Kỹ thuật số, chính xác",
                    "Data/AI/ML cần khoe stack và dự án", "Vai trò không liên quan dữ liệu",
                    "Đề xuất đầu tiên cho dân dữ liệu", false, 13),
                T(14, "devops-stack", "DevOps Stack", "Timeline ngày tháng, nhóm công cụ hạ tầng rõ ràng",
                    "Timeline hạ tầng", "developer", "IT", "DevOps,Cloud,SRE", "all",
                    "DevOps,Infra,Cloud", "modern", 1, true, "#274b73", "Mạch lạc như pipeline CI/CD",
                    "DevOps/Cloud/SRE với nhiều công cụ và chứng chỉ", "Vai trò mềm, ít kỹ thuật",
                    "Khi tool-stack là trọng tâm", false, 14, isActive: false),
                T(15, "product-builder", "Product Builder", "Dự án lên trước, nhấn mạnh kết quả sản phẩm",
                    "Kết quả sản phẩm", "creative", "Sản phẩm,IT", "PM,Product,Freelance", "all",
                    "Product,PM,Freelance", "creative", 1, false, "#7fae9b", "Xanh sage tươi mới, tinh thần xây dựng",
                    "PM/freelance cần chứng minh kết quả", "ATS khắt khe",
                    "Khi outcome quan trọng hơn chức danh", false, 15, isActive: false),
                T(16, "startup-modern", "Startup Modern", "Trẻ trung, gọn nhẹ nhưng vẫn chuyên nghiệp",
                    "Trẻ trung startup", "creative", "all", "all", "fresher",
                    "Startup,Hiện đại,Fresher", "modern", 1, true, "#355c8c", "Trẻ trung mà vẫn đáng tin",
                    "Fresher hoặc startup văn hóa mở", "Tổ chức truyền thống",
                    "Năng động nhưng an toàn", false, 16, isActive: false),
                T(17, "elegant-serif", "Elegant Serif", "Tiêu đề serif trang nhã, thân thiện ATS",
                    "Serif trang nhã", "corporate", "all", "all", "senior",
                    "Serif,Editorial,Premium", "editorial", 1, true, "#2f3440", "Serif cổ điển, tinh tế",
                    "Vai trò cần sự tinh tế, cao cấp", "Kỹ thuật thuần túy (quá mềm)",
                    "Cao cấp mà vẫn qua ATS", false, 17),
                T(18, "minimal-grid", "Minimal Grid", "Mô-đun lưới gọn gàng, cấu trúc thị giác rõ",
                    "Lưới tối giản", "developer", "IT", "Frontend,Fullstack", "all",
                    "Grid,Hiện đại,Gọn", "modern", 2, true, "#274b73", "Lưới trật tự, dễ quét",
                    "Frontend/fullstack thích bố cục module", "Nội dung dài liên tục",
                    "Hiện đại, có cấu trúc", false, 18, isActive: false),
                T(19, "sunset-gradient", "Sunset Gradient", "Header gradient rực rỡ, tên nổi bật cho ngành sáng tạo",
                    "Rực rỡ sáng tạo", "creative", "Marketing,Truyền thông", "Marketing,Content,Social,Event", "all",
                    "Marketing,Content,Social,Branding,Event", "creative", 1, false, "#f97316",
                    "Cam-hồng-tím truyền năng lượng, lạc quan và khác biệt",
                    "Marketing/Content/Social cần gây ấn tượng thị giác", "Ngân hàng, kế toán, hành chính công, ATS khắt khe",
                    "Ấn tượng: rực rỡ, trẻ trung. Đề xuất khi CV có portfolio, branding, dự án sáng tạo", false, 19),
                T(20, "ocean-wave", "Ocean Wave", "Sidebar sóng xanh, timeline thân thiện cho dịch vụ",
                    "Mát mẻ thân thiện", "creative", "Dịch vụ,Du lịch", "Sales,CSKH,Du lịch", "all",
                    "Sales,CSKH,Du lịch,Giao tiếp", "modern", 2, true, "#0284c7",
                    "Xanh biển tin cậy mà tươi mới",
                    "Sales/CSKH/du lịch cần vẻ thân thiện", "Luật, tài chính cấp cao",
                    "Ấn tượng: mát, dễ gần. Đề xuất khi CV nhấn mạnh giao tiếp và phục vụ khách hàng", false, 20),
                T(21, "forest-fresh", "Forest Fresh", "Xanh lá tươi mới, mục tiêu nghề nghiệp dạng quote",
                    "Tươi mới tích cực", "creative", "Giáo dục,Môi trường", "Giáo viên,Content,Tình nguyện", "all",
                    "Môi trường,Giáo dục,NGO,Content", "modern", 1, true, "#16a34a",
                    "Xanh lá tăng trưởng, chân thật",
                    "Giáo dục/môi trường/NGO hoặc fresher cần thiện cảm", "Ngân hàng, chứng khoán",
                    "Ấn tượng: sạch, tích cực. Đề xuất khi CV có hoạt động xã hội, tình nguyện", false, 21),
                T(22, "midnight-pro", "Midnight Pro", "Nền tối, skill tags mono cho dân kỹ thuật",
                    "Nền tối đẳng cấp", "developer", "IT", "Developer,DevOps,Game,AI", "all",
                    "Developer,DevOps,Game,Github", "modern", 1, false, "#0f172a",
                    "Nền tối neon thể hiện đẳng cấp kỹ thuật",
                    "Developer/DevOps/Game muốn phong cách dev-centric", "Hành chính, kế toán, ATS parser cũ",
                    "Ấn tượng: táo bạo, hiện đại. Đề xuất khi CV có Github, opensource, stack sâu", false, 22),
                T(23, "pastel-studio", "Pastel Studio", "Thẻ pastel bo tròn, avatar lớn cho ngành thẩm mỹ",
                    "Nhẹ nhàng tinh tế", "creative", "Thiết kế,Truyền thông", "Designer,UI,UX,Marketing", "all",
                    "Design,UI,UX,Branding,Portfolio", "creative", 2, true, "#f9a8d4",
                    "Pastel nhẹ nhàng, tinh tế",
                    "Designer/UI/UX/Marketing cần vẻ mềm mại", "Luật, tài chính, ATS khắt khe",
                    "Ấn tượng: dễ thương, sáng tạo. Đề xuất khi CV có Figma, portfolio thiết kế", false, 23),
                T(24, "bento-grid", "Bento Grid", "Module lưới bento bất đối xứng kiểu portfolio web",
                    "Module hiện đại", "creative", "IT,Sản phẩm", "Frontend,Product,Designer", "all",
                    "Portfolio,Frontend,Product,Dự án", "modern", 2, true, "#2563eb",
                    "Trật tự trong tự do, cảm giác web hiện đại",
                    "Frontend/Product/Designer khoe dự án theo module", "Hồ sơ dài nhiều chữ",
                    "Ấn tượng: hiện đại như landing page. Đề xuất khi CV giàu dự án", false, 24),
                T(25, "aurora-mesh", "Aurora Mesh", "Nền gradient loang futuristic cho startup và AI",
                    "Tương lai startup", "creative", "Công nghệ,Startup", "Product,AI,Marketing", "all",
                    "Startup,AI,Product,Đổi mới", "creative", 1, false, "#34d399",
                    "Gradient mesh đổi mới, công nghệ",
                    "Startup/AI/Product cần vẻ futuristic", "Corporate truyền thống, ngân hàng",
                    "Ấn tượng: startup, bứt phá. Đề xuất khi CV gắn đổi mới sáng tạo", false, 25),
                T(26, "pop-art-bold", "Pop Art Bold", "Khối màu pop-art, số liệu phóng to kiểu poster",
                    "Bùng nổ cá tính", "creative", "Truyền thông,Quảng cáo", "Quảng cáo,Event,Sales", "all",
                    "Quảng cáo,Event,Sales,Truyền thông", "creative", 1, false, "#facc15",
                    "Vàng-đỏ-cobalt tự tin, bùng nổ",
                    "Quảng cáo/event/sales cần gây nhớ", "Kế toán, luật, y tế",
                    "Ấn tượng: poster khó quên. Đề xuất khi CV cần cá tính mạnh", false, 26),
                T(27, "career-timeline", "Career Timeline", "Trục thời gian dọc kể hành trình thăng tiến",
                    "Hành trình rõ ràng", "corporate", "all", "Manager,Lead", "senior",
                    "Thăng tiến,Quản lý,Kinh nghiệm", "classic", 1, true, "#1e3a5f",
                    "Navy hành trình, tiến bộ vững chắc",
                    "Người có lộ trình thăng tiến rõ", "Fresher (trục trống)",
                    "Ấn tượng: mạch lạc, đáng tin. Đề xuất khi CV nhiều năm kinh nghiệm", false, 27),
                T(28, "infographic-pro", "Infographic Pro", "Thanh/donut % kỹ năng và số liệu trực quan",
                    "Trực quan dữ liệu", "developer", "IT,Marketing", "Data,Marketing,Kế toán", "all",
                    "Kỹ năng,KPI,Data", "modern", 2, false, "#0d9488",
                    "Teal dữ liệu, minh bạch",
                    "CV có kỹ năng định lượng, KPI rõ", "ATS parser text thuần",
                    "Ấn tượng: trực quan, số liệu. Đề xuất khi CV giàu con số", false, 28),
                T(29, "statement-header", "Statement Header", "Header màu đặc, tên khổng lồ khó quên",
                    "Tuyên ngôn cá nhân", "corporate", "all", "Manager,Lead,Sales", "senior",
                    "Quản lý,Thương hiệu cá nhân", "modern", 1, true, "#1e40af",
                    "Một màu đặc quyết đoán",
                    "Quản lý/sales cần thương hiệu cá nhân", "Fresher, ATS tối giản",
                    "Ấn tượng: nhớ tên ngay. Đề xuất khi CV cần dấu ấn lãnh đạo", false, 29),
                T(30, "zen-minimal", "Zen Minimal", "Khoảng trắng cực lớn, không màu accent",
                    "Tĩnh lặng cao cấp", "ats", "all", "all", "all",
                    "Tối giản,Cao cấp", "ats", 1, true, "#111111",
                    "Đen-xám tĩnh, tự tin kiểu Nhật",
                    "Mọi ngành khi muốn tối giản tuyệt đối", "Cần thể hiện cá tính mạnh",
                    "Ấn tượng: cao cấp, tĩnh. An toàn ATS bậc nhất", false, 30),
                T(31, "snapshot-pro", "Snapshot Pro", "Ảnh đại diện lớn, chuẩn CV ảnh thị trường",
                    "Gần gũi đáng tin", "corporate", "Dịch vụ,Giáo dục", "Sales,CSKH,HR,Giáo viên", "all",
                    "Ảnh,Giao tiếp,Dịch vụ", "classic", 2, true, "#c2410c",
                    "Cam đất ấm áp, con người thật",
                    "Sales/CSKH/HR/giáo dục có ảnh đẹp", "Công ty cấm ảnh, ATS ẩn danh",
                    "Ấn tượng: gần gũi. Đề xuất khi CV có ảnh và kỹ năng giao tiếp", false, 31),
                T(32, "one-page-exec", "One-Page Exec", "Ép 1 trang mật độ cao cho lãnh đạo bận rộn",
                    "Súc tích lãnh đạo", "senior", "Quản lý,Tư vấn", "Manager,Director,C-level", "senior",
                    "C-level,Tư vấn,Súc tích", "classic", 2, true, "#0f2a44",
                    "Navy hiệu suất, dồn lực",
                    "C-level/tư vấn cần gọn 1 trang", "Fresher, hồ sơ cần chi tiết",
                    "Ấn tượng: hiệu suất. Đề xuất khi CV dày nhưng cần súc tích", false, 32),
                T(33, "care-plus", "Care Plus", "Header chữ thập y tế, block chứng chỉ hành nghề",
                    "Chuẩn y khoa", "corporate", "Y tế", "Bác sĩ,Điều dưỡng,Dược", "all",
                    "Y tế,Bác sĩ,Điều dưỡng,Chứng chỉ", "classic", 1, true, "#0284c7",
                    "Xanh y tế sạch sẽ, an toàn",
                    "Y tế/dược có chứng chỉ hành nghề", "Ngành khác",
                    "Ấn tượng: chuyên môn y khoa. Đề xuất khi CV có chứng chỉ ngành y", false, 33),
                T(34, "mentor-class", "Mentor Class", "Sidebar thành tích giảng dạy, bảng khóa đào tạo",
                    "Ấm áp tri thức", "corporate", "Giáo dục", "Giáo viên,Giảng viên,Đào tạo", "all",
                    "Giáo viên,Đào tạo,Học thuật", "classic", 2, true, "#ea580c",
                    "Cam ấm tri thức, gần gũi",
                    "Giáo viên/giảng viên/đào tạo nội bộ", "Kỹ thuật thuần",
                    "Ấn tượng: nhà giáo. Đề xuất khi CV có kinh nghiệm giảng dạy", false, 34),
                T(35, "vault-finance", "Vault Finance", "Navy + gold premium, bảng số liệu tài chính",
                    "Premium tài chính", "senior", "Tài chính,Ngân hàng", "Ngân hàng,Tài chính,Kế toán", "senior",
                    "Ngân hàng,Tài chính,CFA", "classic", 1, true, "#c9a227",
                    "Navy-gold giàu có, chính xác",
                    "Ngân hàng/tài chính/kế toán cấp cao", "Startup, sáng tạo",
                    "Ấn tượng: private banking. Đề xuất khi CV có CFA, số liệu tài chính", false, 35),
                T(36, "host-warm", "Host Warm", "Bo tròn thân thiện cho dịch vụ và thực tập",
                    "Dễ mến thân thiện", "fresher", "Dịch vụ,Bán lẻ", "Phục vụ,Bán lẻ,Thực tập", "fresher",
                    "Phục vụ,Bán lẻ,Thực tập", "modern", 1, true, "#fb923c",
                    "Cam đào hiếu khách",
                    "Dịch vụ/bán lẻ/thực tập sinh", "Kỹ thuật, tài chính",
                    "Ấn tượng: dễ mến. Đề xuất khi CV part-time, ít kinh nghiệm", false, 36),
                T(37, "editorial-magazine", "Editorial Magazine", "Bố cục tạp chí, drop-cap và pull-quote",
                    "Tạp chí biên tập", "creative", "Truyền thông,Xuất bản", "Biên tập,Content", "all",
                    "Editorial,Tạp chí,Content", "editorial", 2, true, "#111827", "Mực đen báo chí, đỏ điểm nhấn quyết đoán",
                    "Truyền thông/biên tập cần ấn tượng biên tập", "ATS khắt khe, văn bản thuần túy",
                    "Ấn tượng: tạp chí, trí thức. Đề xuất khi CV viết lách, xuất bản", false, 37),
                T(38, "archi-portfolio", "Archi Portfolio", "Khung bản vẽ kỹ thuật, nhãn sheet",
                    "Bản vẽ kiến trúc", "creative", "Kiến trúc,Xây dựng", "Kiến trúc sư,Nội thất", "all",
                    "Kiến trúc,Bản vẽ,Portfolio", "creative", 2, true, "#334155", "Xám thép chính xác, kỷ luật",
                    "Kiến trúc/nội thất khoe bản vẽ", "Vai trò phi thiết kế",
                    "Ấn tượng: kỹ thuật, chuẩn xác. Đề xuất khi CV có portfolio bản vẽ", false, 38),
                T(39, "legal-prestige", "Legal Prestige", "Trang trọng, điều khoản đánh số La Mã",
                    "Uy nghi ngành luật", "corporate", "Luật", "Luật sư,Pháp chế", "all",
                    "Luật,Pháp chế", "classic", 1, true, "#1e3a5f", "Navy uy quyền, gold trang trọng",
                    "Luật/pháp chế cần sự tin cậy", "Startup, sáng tạo",
                    "Ấn tượng: uy nghi. Đề xuất khi CV luật, tuân thủ", false, 39),
                T(40, "motion-creative", "Motion Creative", "Band nghiêng, khối chuyển động",
                    "Năng động đa phương tiện", "creative", "Truyền thông,Giải trí", "Multimedia,Content", "all",
                    "Sáng tạo,Multimedia", "creative", 1, false, "#f43f5e", "Coral-violet trẻ trung, chuyển động",
                    "Multimedia/content cần năng lượng", "Luật, tài chính, ATS khắt khe",
                    "Ấn tượng: động, trẻ. Đề xuất khi CV sáng tạo nội dung số", false, 40),
                T(41, "research-scholar", "Research Scholar", "Abstract, citation và metrics học thuật",
                    "Học thuật chuyên sâu", "senior", "Giáo dục,Nghiên cứu", "Nghiên cứu,Giảng viên", "senior",
                    "Nghiên cứu,Học thuật", "classic", 2, true, "#14532d", "Xanh lá đậm học thuật, nghiêm cẩn",
                    "Nghiên cứu/giảng viên có công bố", "Doanh nghiệp thương mại",
                    "Ấn tượng: học giả. Đề xuất khi CV có công bố, đề tài", false, 41),
                T(42, "culinary-signature", "Culinary Signature", "Phong cách menu nhà hàng cao cấp",
                    "Ẩm thực đẳng cấp", "creative", "F&B,Du lịch", "Đầu bếp,F&B", "all",
                    "F&B,Đầu bếp", "creative", 1, true, "#881337", "Burgundy ấm cúng, tinh tế",
                    "Đầu bếp/F&B cần dấu ấn riêng", "Kỹ thuật, văn phòng",
                    "Ấn tượng: ngon mắt. Đề xuất khi CV ẩm thực, nhà hàng", false, 42),
                T(43, "fashion-editorial", "Fashion Editorial", "Lookbook, type-scale thời trang",
                    "Thời trang cao cấp", "creative", "Thời trang", "Thiết kế,Stylist", "all",
                    "Thời trang,Lookbook", "editorial", 1, false, "#0a0a0a", "Đen-trắng tương phản, thời thượng",
                    "Thời trang/stylist cần gu thẩm mỹ", "ATS khắt khe, văn phòng truyền thống",
                    "Ấn tượng: lookbook. Đề xuất khi CV thời trang, phong cách", false, 43),
                T(44, "industrial-blueprint", "Industrial Blueprint", "Lưới blueprint, specs-table kỹ thuật",
                    "Kỹ thuật công nghiệp", "developer", "Cơ khí,Sản xuất", "Kỹ sư,Cơ khí", "all",
                    "Cơ khí,Bản vẽ,Kỹ thuật", "modern", 1, true, "#475569", "Xám thép công nghiệp, chính xác",
                    "Cơ khí/sản xuất cần tính kỹ thuật", "Sáng tạo, dịch vụ",
                    "Ấn tượng: bản vẽ kỹ thuật. Đề xuất khi CV công nghiệp, nhà máy", false, 44));
        }
    }
}
