import Link from "next/link";
import { ArrowUpRight, BriefcaseBusiness, MapPin, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { Job } from "@/features/viec-lam/types";

export function CompanyJobList({ jobs, loading, matchScores }: { jobs: Job[]; loading: boolean; matchScores: Record<string, number> }) {
  return <Card><CardHeader className="flex-row items-center justify-between"><CardTitle className="flex items-center gap-2 text-lg"><BriefcaseBusiness className="size-4 text-primary" />Việc làm đang tuyển</CardTitle><Badge variant="secondary">{jobs.length}</Badge></CardHeader><CardContent>{loading ? <p className="text-sm text-muted-foreground">Đang tải việc làm...</p> : jobs.length === 0 ? <p className="rounded-xl border border-dashed border-border p-6 text-center text-sm text-muted-foreground">Doanh nghiệp hiện chưa có việc làm đang mở.</p> : <div className="space-y-3">{jobs.map((job) => { const score = matchScores[job.id]; return <Link key={job.id} href={`/viec-lam/${job.id}`} className="group block rounded-2xl border border-border p-4 transition-colors hover:border-primary/35 hover:bg-muted/30"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><h3 className="font-semibold group-hover:text-primary">{job.title}</h3><p className="mt-1 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><MapPin className="size-3" />{job.location}</span><span>{job.salary}</span></p></div>{score != null && <Badge className="shrink-0 gap-1.5"><Sparkles className="size-3" />{Math.round(score)}% phù hợp</Badge>}</div><div className="mt-3 flex items-center justify-between"><div className="flex flex-wrap gap-1.5">{job.skills.slice(0, 4).map((skill) => <Badge key={skill} variant="secondary">{skill}</Badge>)}</div><ArrowUpRight className="size-4 shrink-0 text-muted-foreground group-hover:text-primary" /></div></Link>; })}</div>}</CardContent></Card>;
}
