using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Pgvector;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddCvThemes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("Npgsql:PostgresExtension:vector", ",,");

            migrationBuilder.CreateTable(
                name: "cv_themes",
                columns: table => new
                {
                    Id = table.Column<int>(type: "integer", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", Npgsql.EntityFrameworkCore.PostgreSQL.Metadata.NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    Slug = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                    Ten = table.Column<string>(type: "character varying(255)", maxLength: 255, nullable: false),
                    MoTa = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    MoTaNgan = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                    PreviewStorageKey = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    DanhMuc = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    NganhPhuHop = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    ViTriMucTieu = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    CapBac = table.Column<string>(type: "character varying(50)", maxLength: 50, nullable: true),
                    Tags = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    PhongCachThietKe = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    SoCot = table.Column<int>(type: "integer", nullable: false),
                    ThanThienATS = table.Column<bool>(type: "boolean", nullable: false),
                    MauSacChuDao = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    TamLyMauSac = table.Column<string>(type: "character varying(500)", maxLength: 500, nullable: true),
                    KhuyenNghiSuDung = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
                    TranhSuDungKhi = table.Column<string>(type: "character varying(1000)", maxLength: 1000, nullable: true),
                    GoiYAI = table.Column<string>(type: "text", nullable: true),
                    LaMacDinh = table.Column<bool>(type: "boolean", nullable: false),
                    IsActive = table.Column<bool>(type: "boolean", nullable: false),
                    ThuTu = table.Column<int>(type: "integer", nullable: false),
                    EmbeddingModel = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: true),
                    Embedding = table.Column<Pgvector.Vector>(type: "vector(1536)", nullable: true),
                    CreatedBy = table.Column<string>(type: "text", nullable: true),
                    Created = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    LastModifiedBy = table.Column<string>(type: "text", nullable: true),
                    LastModified = table.Column<DateTime>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_cv_themes", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "cv_themes",
                columns: new[] { "CapBac", "Created", "CreatedBy", "DanhMuc", "Embedding", "EmbeddingModel", "GoiYAI", "Id", "IsActive", "KhuyenNghiSuDung", "LaMacDinh", "LastModified", "LastModifiedBy", "MauSacChuDao", "MoTa", "MoTaNgan", "NganhPhuHop", "PhongCachThietKe", "PreviewStorageKey", "Slug", "SoCot", "TamLyMauSac", "Tags", "Ten", "ThanThienATS", "ThuTu", "TranhSuDungKhi", "ViTriMucTieu" },
                values: new object[,]
                {
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "ats", null, null, "Mặc định an toàn khi không rõ yêu cầu nhà tuyển dụng", 1, true, "Mọi ngành, đặc biệt khi nộp qua hệ thống ATS", true, null, null, "#1f2a37", "Một cột, tương thích hệ thống lọc hồ sơ", "Chuẩn ATS, an toàn mọi ngành", "all", "ats", null, "minimal-ats", 1, "Đen than tạo cảm giác tin cậy, tập trung nội dung", "ATS,Professional", "Minimal ATS", true, 1, "Portfolio sáng tạo cần ấn tượng thị giác mạnh", "all" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "developer", null, null, "Đề xuất đầu tiên cho hồ sơ kỹ thuật", 2, true, "IT/Developer cần nêu bật dự án và kỹ năng", false, null, null, "#274b73", "Hai cột, dành cho IT / Developer", "Chuẩn IT, sidebar kỹ năng", "IT", "modern", null, "tech-modern", 2, "Xanh navy truyền tải chuyên nghiệp và đáng tin", "IT,Developer", "Tech Modern", true, 2, "Môi trường bảo thủ hoặc văn bản thuần túy", "Backend,Frontend,Fullstack,DevOps" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "ats", null, null, "Bản ATS gọn hơn minimal-ats cho dân kỹ thuật", 3, true, "Backend/DevOps/Data nộp qua cổng ATS", false, null, null, "#1f2a37", "Một cột gọn nhẹ, tối ưu hệ thống lọc hồ sơ", "Gọn nhẹ, qua ATS dễ dàng", "IT", "classic", null, "ats-classic", 1, "Tối giản, máy đọc ưu tiên", "ATS,Backend,DevOps", "ATS Classic", true, 3, "Vai trò cần thể hiện cá tính mạnh", "Backend,DevOps,Data" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "developer", null, null, "Khi cần 2 cột nhưng vẫn giữ vẻ trang trọng", 4, true, "IT/BA/PM cần cân bằng kỹ năng và kinh nghiệm", false, null, null, "#274b73", "Hai cột thanh lịch, sidebar hẹp cho IT / BA / PM", "Thanh lịch 2 cột", "IT,Kinh doanh", "modern", null, "professional-split", 2, "Navy điểm xuyết tạo chiều sâu chuyên nghiệp", "IT,2 cột,Chuyên nghiệp", "Professional Split", true, 4, "Fresher ít nội dung (sidebar sẽ trống)", "Backend,BA,PM" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "developer", null, null, "Cho vai trò cần năng lượng hiện đại", 5, true, "Product/Frontend muốn nổi bật dự án", false, null, null, "#274b73", "Hiện đại, điểm nhấn mạnh cho Product / Frontend", "Điểm nhấn hiện đại", "IT,Sản phẩm", "modern", null, "modern-accent", 1, "Điểm nhấn màu dẫn mắt vào thành tựu", "Hiện đại,Frontend,Product", "Modern Accent", true, 5, "Hồ sơ học thuật hoặc hành chính", "Frontend,Product" },
                    { "senior", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "senior", null, null, "Khi cần thể hiện đẳng cấp lãnh đạo", 6, true, "Senior/lead ứng tuyển vị trí quản lý kỹ thuật", false, null, null, "#1f2a37", "Bố cục doanh nghiệp trang trọng cho senior / lead", "Trang trọng cho lead", "IT,Quản lý", "classic", null, "executive-tech", 1, "Trang trọng, thể hiện tầm vóc quản lý", "Senior,Chuyên nghiệp,Lead", "Executive Tech", true, 6, "Fresher/junior (quá nặng nề)", "Lead,Manager,Architect" },
                    { "fresher", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "developer", null, null, "Tối ưu 1 trang cho người mới", 7, false, "Fresher/junior ít kinh nghiệm nhưng nhiều kỹ năng", false, null, null, "#1f2a37", "Một cột siêu gọn cho fresher / junior IT", "Siêu gọn cho fresher", "IT", "ats", null, "compact-developer", 1, "Gọn gàng, không phô trương", "ATS,Fresher,Junior", "Compact Developer", true, 7, "Senior có bề dày cần không gian", "Backend,Frontend,Fresher" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "developer", null, null, "Khi kỹ năng là điểm mạnh nhất", 8, false, "IT generalist muốn khoe stack kỹ năng", false, null, null, "#274b73", "Sidebar phải, kỹ năng đặt lên đầu cho IT", "Kỹ năng lên đầu", "IT", "modern", null, "sidebar-pro", 2, "Sidebar điều hướng mắt nhà tuyển dụng", "IT,2 cột,Kỹ năng", "Sidebar Pro", true, 8, "Vai trò phi kỹ thuật", "Backend,Frontend,Fullstack" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "corporate", null, null, "An toàn cho khối văn phòng", 9, false, "BA/PM/QA/HR trong môi trường corporate", false, null, null, "#1f2a37", "Phong cách công sở chuẩn mực cho BA / PM / QA / HR", "Chuẩn công sở", "Kinh doanh,Hành chính", "classic", null, "clean-corporate", 1, "Chuẩn mực, phù hợp văn hóa doanh nghiệp", "Corporate,BA,PM", "Clean Corporate", true, 9, "Sáng tạo, startup (quá cứng nhắc)", "BA,PM,QA,HR" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "creative", null, null, "Khi portfolio quan trọng hơn từ ngữ", 10, true, "Designer/frontend cần show dự án trực quan", false, null, null, "#7a3b4d", "Cá tính mạnh, dự án dạng thẻ cho designer / frontend", "Cá tính portfolio", "Thiết kế,IT", "creative", null, "creative-portfolio", 1, "Đỏ burgundy khơi gợi sáng tạo và đam mê", "Creative,Portfolio,Designer", "Creative Portfolio", false, 10, "Nộp qua ATS nghiêm ngặt", "Designer,Frontend" },
                    { "senior", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "senior", null, null, "Cho hồ sơ lãnh đạo dày dặn", 11, false, "Quản lý cấp cao với bề dày thành tích", false, null, null, "#1f2a37", "Thoáng đãng, tôn vinh kinh nghiệm lãnh đạo", "Lãnh đạo thoáng đãng", "Quản lý", "classic", null, "senior-executive", 1, "Khoảng trắng thể hiện sự tự tin", "Senior,Leadership,Manager", "Senior Executive", true, 11, "Người mới (thiếu nội dung sẽ lộ)", "Manager,Director,C-level" },
                    { "fresher", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "ats", null, null, "Khi học vấn là tài sản lớn nhất", 12, true, "Học thuật, nghiên cứu, học bổng", false, null, null, "#1f2a37", "Học vấn lên trước, đánh số nghiên cứu / chứng chỉ", "Học thuật chuẩn", "Giáo dục,Nghiên cứu", "ats", null, "academic-cv", 1, "Hàn lâm, nghiêm túc", "Academic,Research,Học vấn", "Academic CV", true, 12, "Doanh nghiệp thương mại (quá khô)", "Nghiên cứu,Học thuật" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "developer", null, null, "Đề xuất đầu tiên cho dân dữ liệu", 13, true, "Data/AI/ML cần khoe stack và dự án", false, null, null, "#274b73", "Dải stack nổi bật, dự án dẫn đầu cho Data / AI / ML", "Chuyên Data/AI", "Data,IT", "modern", null, "data-specialist", 1, "Kỹ thuật số, chính xác", "Data,AI,ML", "Data Specialist", true, 13, "Vai trò không liên quan dữ liệu", "Data,AI,ML" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "developer", null, null, "Khi tool-stack là trọng tâm", 14, false, "DevOps/Cloud/SRE với nhiều công cụ và chứng chỉ", false, null, null, "#274b73", "Timeline ngày tháng, nhóm công cụ hạ tầng rõ ràng", "Timeline hạ tầng", "IT", "modern", null, "devops-stack", 1, "Mạch lạc như pipeline CI/CD", "DevOps,Infra,Cloud", "DevOps Stack", true, 14, "Vai trò mềm, ít kỹ thuật", "DevOps,Cloud,SRE" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "creative", null, null, "Khi outcome quan trọng hơn chức danh", 15, false, "PM/freelance cần chứng minh kết quả", false, null, null, "#7fae9b", "Dự án lên trước, nhấn mạnh kết quả sản phẩm", "Kết quả sản phẩm", "Sản phẩm,IT", "creative", null, "product-builder", 1, "Xanh sage tươi mới, tinh thần xây dựng", "Product,PM,Freelance", "Product Builder", false, 15, "ATS khắt khe", "PM,Product,Freelance" },
                    { "fresher", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "creative", null, null, "Năng động nhưng an toàn", 16, false, "Fresher hoặc startup văn hóa mở", false, null, null, "#355c8c", "Trẻ trung, gọn nhẹ nhưng vẫn chuyên nghiệp", "Trẻ trung startup", "all", "modern", null, "startup-modern", 1, "Trẻ trung mà vẫn đáng tin", "Startup,Hiện đại,Fresher", "Startup Modern", true, 16, "Tổ chức truyền thống", "all" },
                    { "senior", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "corporate", null, null, "Cao cấp mà vẫn qua ATS", 17, true, "Vai trò cần sự tinh tế, cao cấp", false, null, null, "#2f3440", "Tiêu đề serif trang nhã, thân thiện ATS", "Serif trang nhã", "all", "editorial", null, "elegant-serif", 1, "Serif cổ điển, tinh tế", "Serif,Editorial,Premium", "Elegant Serif", true, 17, "Kỹ thuật thuần túy (quá mềm)", "all" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "developer", null, null, "Hiện đại, có cấu trúc", 18, false, "Frontend/fullstack thích bố cục module", false, null, null, "#274b73", "Mô-đun lưới gọn gàng, cấu trúc thị giác rõ", "Lưới tối giản", "IT", "modern", null, "minimal-grid", 2, "Lưới trật tự, dễ quét", "Grid,Hiện đại,Gọn", "Minimal Grid", true, 18, "Nội dung dài liên tục", "Frontend,Fullstack" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "creative", null, null, "Ấn tượng: rực rỡ, trẻ trung. Đề xuất khi CV có portfolio, branding, dự án sáng tạo", 19, true, "Marketing/Content/Social cần gây ấn tượng thị giác", false, null, null, "#f97316", "Header gradient rực rỡ, tên nổi bật cho ngành sáng tạo", "Rực rỡ sáng tạo", "Marketing,Truyền thông", "creative", null, "sunset-gradient", 1, "Cam-hồng-tím truyền năng lượng, lạc quan và khác biệt", "Marketing,Content,Social,Branding,Event", "Sunset Gradient", false, 19, "Ngân hàng, kế toán, hành chính công, ATS khắt khe", "Marketing,Content,Social,Event" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "creative", null, null, "Ấn tượng: mát, dễ gần. Đề xuất khi CV nhấn mạnh giao tiếp và phục vụ khách hàng", 20, true, "Sales/CSKH/du lịch cần vẻ thân thiện", false, null, null, "#0284c7", "Sidebar sóng xanh, timeline thân thiện cho dịch vụ", "Mát mẻ thân thiện", "Dịch vụ,Du lịch", "modern", null, "ocean-wave", 2, "Xanh biển tin cậy mà tươi mới", "Sales,CSKH,Du lịch,Giao tiếp", "Ocean Wave", true, 20, "Luật, tài chính cấp cao", "Sales,CSKH,Du lịch" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "creative", null, null, "Ấn tượng: sạch, tích cực. Đề xuất khi CV có hoạt động xã hội, tình nguyện", 21, true, "Giáo dục/môi trường/NGO hoặc fresher cần thiện cảm", false, null, null, "#16a34a", "Xanh lá tươi mới, mục tiêu nghề nghiệp dạng quote", "Tươi mới tích cực", "Giáo dục,Môi trường", "modern", null, "forest-fresh", 1, "Xanh lá tăng trưởng, chân thật", "Môi trường,Giáo dục,NGO,Content", "Forest Fresh", true, 21, "Ngân hàng, chứng khoán", "Giáo viên,Content,Tình nguyện" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "developer", null, null, "Ấn tượng: táo bạo, hiện đại. Đề xuất khi CV có Github, opensource, stack sâu", 22, true, "Developer/DevOps/Game muốn phong cách dev-centric", false, null, null, "#0f172a", "Nền tối, skill tags mono cho dân kỹ thuật", "Nền tối đẳng cấp", "IT", "modern", null, "midnight-pro", 1, "Nền tối neon thể hiện đẳng cấp kỹ thuật", "Developer,DevOps,Game,Github", "Midnight Pro", false, 22, "Hành chính, kế toán, ATS parser cũ", "Developer,DevOps,Game,AI" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "creative", null, null, "Ấn tượng: dễ thương, sáng tạo. Đề xuất khi CV có Figma, portfolio thiết kế", 23, true, "Designer/UI/UX/Marketing cần vẻ mềm mại", false, null, null, "#f9a8d4", "Thẻ pastel bo tròn, avatar lớn cho ngành thẩm mỹ", "Nhẹ nhàng tinh tế", "Thiết kế,Truyền thông", "creative", null, "pastel-studio", 2, "Pastel nhẹ nhàng, tinh tế", "Design,UI,UX,Branding,Portfolio", "Pastel Studio", true, 23, "Luật, tài chính, ATS khắt khe", "Designer,UI,UX,Marketing" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "creative", null, null, "Ấn tượng: hiện đại như landing page. Đề xuất khi CV giàu dự án", 24, true, "Frontend/Product/Designer khoe dự án theo module", false, null, null, "#2563eb", "Module lưới bento bất đối xứng kiểu portfolio web", "Module hiện đại", "IT,Sản phẩm", "modern", null, "bento-grid", 2, "Trật tự trong tự do, cảm giác web hiện đại", "Portfolio,Frontend,Product,Dự án", "Bento Grid", true, 24, "Hồ sơ dài nhiều chữ", "Frontend,Product,Designer" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "creative", null, null, "Ấn tượng: startup, bứt phá. Đề xuất khi CV gắn đổi mới sáng tạo", 25, true, "Startup/AI/Product cần vẻ futuristic", false, null, null, "#34d399", "Nền gradient loang futuristic cho startup và AI", "Tương lai startup", "Công nghệ,Startup", "creative", null, "aurora-mesh", 1, "Gradient mesh đổi mới, công nghệ", "Startup,AI,Product,Đổi mới", "Aurora Mesh", false, 25, "Corporate truyền thống, ngân hàng", "Product,AI,Marketing" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "creative", null, null, "Ấn tượng: poster khó quên. Đề xuất khi CV cần cá tính mạnh", 26, true, "Quảng cáo/event/sales cần gây nhớ", false, null, null, "#facc15", "Khối màu pop-art, số liệu phóng to kiểu poster", "Bùng nổ cá tính", "Truyền thông,Quảng cáo", "creative", null, "pop-art-bold", 1, "Vàng-đỏ-cobalt tự tin, bùng nổ", "Quảng cáo,Event,Sales,Truyền thông", "Pop Art Bold", false, 26, "Kế toán, luật, y tế", "Quảng cáo,Event,Sales" },
                    { "senior", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "corporate", null, null, "Ấn tượng: mạch lạc, đáng tin. Đề xuất khi CV nhiều năm kinh nghiệm", 27, true, "Người có lộ trình thăng tiến rõ", false, null, null, "#1e3a5f", "Trục thời gian dọc kể hành trình thăng tiến", "Hành trình rõ ràng", "all", "classic", null, "career-timeline", 1, "Navy hành trình, tiến bộ vững chắc", "Thăng tiến,Quản lý,Kinh nghiệm", "Career Timeline", true, 27, "Fresher (trục trống)", "Manager,Lead" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "developer", null, null, "Ấn tượng: trực quan, số liệu. Đề xuất khi CV giàu con số", 28, true, "CV có kỹ năng định lượng, KPI rõ", false, null, null, "#0d9488", "Thanh/donut % kỹ năng và số liệu trực quan", "Trực quan dữ liệu", "IT,Marketing", "modern", null, "infographic-pro", 2, "Teal dữ liệu, minh bạch", "Kỹ năng,KPI,Data", "Infographic Pro", false, 28, "ATS parser text thuần", "Data,Marketing,Kế toán" },
                    { "senior", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "corporate", null, null, "Ấn tượng: nhớ tên ngay. Đề xuất khi CV cần dấu ấn lãnh đạo", 29, true, "Quản lý/sales cần thương hiệu cá nhân", false, null, null, "#1e40af", "Header màu đặc, tên khổng lồ khó quên", "Tuyên ngôn cá nhân", "all", "modern", null, "statement-header", 1, "Một màu đặc quyết đoán", "Quản lý,Thương hiệu cá nhân", "Statement Header", true, 29, "Fresher, ATS tối giản", "Manager,Lead,Sales" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "ats", null, null, "Ấn tượng: cao cấp, tĩnh. An toàn ATS bậc nhất", 30, true, "Mọi ngành khi muốn tối giản tuyệt đối", false, null, null, "#111111", "Khoảng trắng cực lớn, không màu accent", "Tĩnh lặng cao cấp", "all", "ats", null, "zen-minimal", 1, "Đen-xám tĩnh, tự tin kiểu Nhật", "Tối giản,Cao cấp", "Zen Minimal", true, 30, "Cần thể hiện cá tính mạnh", "all" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "corporate", null, null, "Ấn tượng: gần gũi. Đề xuất khi CV có ảnh và kỹ năng giao tiếp", 31, true, "Sales/CSKH/HR/giáo dục có ảnh đẹp", false, null, null, "#c2410c", "Ảnh đại diện lớn, chuẩn CV ảnh thị trường", "Gần gũi đáng tin", "Dịch vụ,Giáo dục", "classic", null, "snapshot-pro", 2, "Cam đất ấm áp, con người thật", "Ảnh,Giao tiếp,Dịch vụ", "Snapshot Pro", true, 31, "Công ty cấm ảnh, ATS ẩn danh", "Sales,CSKH,HR,Giáo viên" },
                    { "senior", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "senior", null, null, "Ấn tượng: hiệu suất. Đề xuất khi CV dày nhưng cần súc tích", 32, true, "C-level/tư vấn cần gọn 1 trang", false, null, null, "#0f2a44", "Ép 1 trang mật độ cao cho lãnh đạo bận rộn", "Súc tích lãnh đạo", "Quản lý,Tư vấn", "classic", null, "one-page-exec", 2, "Navy hiệu suất, dồn lực", "C-level,Tư vấn,Súc tích", "One-Page Exec", true, 32, "Fresher, hồ sơ cần chi tiết", "Manager,Director,C-level" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "corporate", null, null, "Ấn tượng: chuyên môn y khoa. Đề xuất khi CV có chứng chỉ ngành y", 33, true, "Y tế/dược có chứng chỉ hành nghề", false, null, null, "#0284c7", "Header chữ thập y tế, block chứng chỉ hành nghề", "Chuẩn y khoa", "Y tế", "classic", null, "care-plus", 1, "Xanh y tế sạch sẽ, an toàn", "Y tế,Bác sĩ,Điều dưỡng,Chứng chỉ", "Care Plus", true, 33, "Ngành khác", "Bác sĩ,Điều dưỡng,Dược" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "corporate", null, null, "Ấn tượng: nhà giáo. Đề xuất khi CV có kinh nghiệm giảng dạy", 34, true, "Giáo viên/giảng viên/đào tạo nội bộ", false, null, null, "#ea580c", "Sidebar thành tích giảng dạy, bảng khóa đào tạo", "Ấm áp tri thức", "Giáo dục", "classic", null, "mentor-class", 2, "Cam ấm tri thức, gần gũi", "Giáo viên,Đào tạo,Học thuật", "Mentor Class", true, 34, "Kỹ thuật thuần", "Giáo viên,Giảng viên,Đào tạo" },
                    { "senior", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "senior", null, null, "Ấn tượng: private banking. Đề xuất khi CV có CFA, số liệu tài chính", 35, true, "Ngân hàng/tài chính/kế toán cấp cao", false, null, null, "#c9a227", "Navy + gold premium, bảng số liệu tài chính", "Premium tài chính", "Tài chính,Ngân hàng", "classic", null, "vault-finance", 1, "Navy-gold giàu có, chính xác", "Ngân hàng,Tài chính,CFA", "Vault Finance", true, 35, "Startup, sáng tạo", "Ngân hàng,Tài chính,Kế toán" },
                    { "fresher", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "fresher", null, null, "Ấn tượng: dễ mến. Đề xuất khi CV part-time, ít kinh nghiệm", 36, true, "Dịch vụ/bán lẻ/thực tập sinh", false, null, null, "#fb923c", "Bo tròn thân thiện cho dịch vụ và thực tập", "Dễ mến thân thiện", "Dịch vụ,Bán lẻ", "modern", null, "host-warm", 1, "Cam đào hiếu khách", "Phục vụ,Bán lẻ,Thực tập", "Host Warm", true, 36, "Kỹ thuật, tài chính", "Phục vụ,Bán lẻ,Thực tập", },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "creative", null, null, "Ấn tượng: tạp chí, trí thức. Đề xuất khi CV viết lách, xuất bản", 37, true, "Truyền thông/biên tập cần ấn tượng biên tập", false, null, null, "#111827", "Bố cục tạp chí, drop-cap và pull-quote", "Tạp chí biên tập", "Truyền thông,Xuất bản", "editorial", null, "editorial-magazine", 2, "Mực đen báo chí, đỏ điểm nhấn quyết đoán", "Editorial,Tạp chí,Content", "Editorial Magazine", true, 37, "ATS khắt khe, văn bản thuần túy", "Biên tập,Content" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "creative", null, null, "Ấn tượng: kỹ thuật, chuẩn xác. Đề xuất khi CV có portfolio bản vẽ", 38, true, "Kiến trúc/nội thất khoe bản vẽ", false, null, null, "#334155", "Khung bản vẽ kỹ thuật, nhãn sheet", "Bản vẽ kiến trúc", "Kiến trúc,Xây dựng", "creative", null, "archi-portfolio", 2, "Xám thép chính xác, kỷ luật", "Kiến trúc,Bản vẽ,Portfolio", "Archi Portfolio", true, 38, "Vai trò phi thiết kế", "Kiến trúc sư,Nội thất" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "corporate", null, null, "Ấn tượng: uy nghi. Đề xuất khi CV luật, tuân thủ", 39, true, "Luật/pháp chế cần sự tin cậy", false, null, null, "#1e3a5f", "Trang trọng, điều khoản đánh số La Mã", "Uy nghi ngành luật", "Luật", "classic", null, "legal-prestige", 1, "Navy uy quyền, gold trang trọng", "Luật,Pháp chế", "Legal Prestige", true, 39, "Startup, sáng tạo", "Luật sư,Pháp chế" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "creative", null, null, "Ấn tượng: động, trẻ. Đề xuất khi CV sáng tạo nội dung số", 40, true, "Multimedia/content cần năng lượng", false, null, null, "#f43f5e", "Band nghiêng, khối chuyển động", "Năng động đa phương tiện", "Truyền thông,Giải trí", "creative", null, "motion-creative", 1, "Coral-violet trẻ trung, chuyển động", "Sáng tạo,Multimedia", "Motion Creative", false, 40, "Luật, tài chính, ATS khắt khe", "Multimedia,Content" },
                    { "senior", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "senior", null, null, "Ấn tượng: học giả. Đề xuất khi CV có công bố, đề tài", 41, true, "Nghiên cứu/giảng viên có công bố", false, null, null, "#14532d", "Abstract, citation và metrics học thuật", "Học thuật chuyên sâu", "Giáo dục,Nghiên cứu", "classic", null, "research-scholar", 2, "Xanh lá đậm học thuật, nghiêm cẩn", "Nghiên cứu,Học thuật", "Research Scholar", true, 41, "Doanh nghiệp thương mại", "Nghiên cứu,Giảng viên" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "creative", null, null, "Ấn tượng: ngon mắt. Đề xuất khi CV ẩm thực, nhà hàng", 42, true, "Đầu bếp/F&B cần dấu ấn riêng", false, null, null, "#881337", "Phong cách menu nhà hàng cao cấp", "Ẩm thực đẳng cấp", "F&B,Du lịch", "creative", null, "culinary-signature", 1, "Burgundy ấm cúng, tinh tế", "F&B,Đầu bếp", "Culinary Signature", true, 42, "Kỹ thuật, văn phòng", "Đầu bếp,F&B" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "creative", null, null, "Ấn tượng: lookbook. Đề xuất khi CV thời trang, phong cách", 43, true, "Thời trang/stylist cần gu thẩm mỹ", false, null, null, "#0a0a0a", "Lookbook, type-scale thời trang", "Thời trang cao cấp", "Thời trang", "editorial", null, "fashion-editorial", 1, "Đen-trắng tương phản, thời thượng", "Thời trang,Lookbook", "Fashion Editorial", false, 43, "ATS khắt khe, văn phòng truyền thống", "Thiết kế,Stylist" },
                    { "all", new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Utc), "system", "developer", null, null, "Ấn tượng: bản vẽ kỹ thuật. Đề xuất khi CV công nghiệp, nhà máy", 44, true, "Cơ khí/sản xuất cần tính kỹ thuật", false, null, null, "#475569", "Lưới blueprint, specs-table kỹ thuật", "Kỹ thuật công nghiệp", "Cơ khí,Sản xuất", "modern", null, "industrial-blueprint", 1, "Xám thép công nghiệp, chính xác", "Cơ khí,Bản vẽ,Kỹ thuật", "Industrial Blueprint", true, 44, "Sáng tạo, dịch vụ", "Kỹ sư,Cơ khí" },
                });

            migrationBuilder.CreateIndex(
                name: "IX_cv_themes_Slug",
                table: "cv_themes",
                column: "Slug",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "cv_themes");
        }
    }
}
