using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddKyNangUngVienTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Bảng KyNangUngVien có entity + configuration từ trước nhưng chưa từng
            // được tạo trong DB (snapshot có, migration cũ không). Tạo idempotent.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""KyNangUngVien"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""HoSoUngVienId"" integer NOT NULL,
                    ""KyNangId"" integer NOT NULL,
                    ""SoNamKinhNghiem"" real,
                    ""MucDoThongThao"" character varying(50) NOT NULL,
                    ""CreatedBy"" text,
                    ""Created"" timestamp with time zone NOT NULL,
                    ""LastModifiedBy"" text,
                    ""LastModified"" timestamp with time zone,
                    CONSTRAINT ""PK_KyNangUngVien"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_KyNangUngVien_HoSoUngVien_HoSoUngVienId"" FOREIGN KEY (""HoSoUngVienId"")
                        REFERENCES ""HoSoUngVien"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_KyNangUngVien_KyNang_KyNangId"" FOREIGN KEY (""KyNangId"")
                        REFERENCES ""KyNang"" (""Id"") ON DELETE RESTRICT
                );
                CREATE UNIQUE INDEX IF NOT EXISTS ""IX_KyNangUngVien_HoSoUngVienId_KyNangId"" ON ""KyNangUngVien"" (""HoSoUngVienId"", ""KyNangId"");
                CREATE INDEX IF NOT EXISTS ""IX_KyNangUngVien_HoSoUngVienId"" ON ""KyNangUngVien"" (""HoSoUngVienId"");
                CREATE INDEX IF NOT EXISTS ""IX_KyNangUngVien_KyNangId"" ON ""KyNangUngVien"" (""KyNangId"");
            ");

            migrationBuilder.AlterColumn<int>(
                name: "TepDaSinhId",
                table: "CVPhienBan",
                type: "integer",
                nullable: true,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AddColumn<string>(
                name: "TemplateVersion",
                table: "CVPhienBan",
                type: "text",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""KyNangUngVien"";");

            migrationBuilder.DropColumn(
                name: "TemplateVersion",
                table: "CVPhienBan");

            migrationBuilder.AlterColumn<int>(
                name: "TepDaSinhId",
                table: "CVPhienBan",
                type: "integer",
                nullable: false,
                defaultValue: 0,
                oldClrType: typeof(int),
                oldType: "integer",
                oldNullable: true);
        }
    }
}
