// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260821042215_LinkNguoiDungToIdentity")]
    partial class LinkNguoiDungToIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.cvUngVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("fileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("hoSoUngVienId")
                        .HasColumnType("integer");

                    b.Property<bool>("is_Default")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ngayUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("tenFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("hoSoUngVienId");

                    b.ToTable("cvUngVien", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.danhGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("donUngTuyenId")
                        .HasColumnType("integer");

                    b.Property<string>("ketLuan")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ngayPhanHoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("noiDungPhanHoi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("danhGias");
                });

            modelBuilder.Entity("Domain.Entities.danhMucNghe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("moTa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("tenNghe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("tenNghe")
                        .IsUnique();

                    b.ToTable("danhMucNghe", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.doanhNghiep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("diaChi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("logoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("moTa")
                        .HasColumnType("text");

                    b.Property<string>("tenDoanhNghiep")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("doanhNghiep", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.donUngTuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("cvUngVienId")
                        .HasColumnType("integer");

                    b.Property<int>("hoSoUngVienId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ngayUngTuyen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("tinTuyenDungId")
                        .HasColumnType("integer");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("cvUngVienId");

                    b.HasIndex("hoSoUngVienId");

                    b.HasIndex("tinTuyenDungId");

                    b.ToTable("donUngTuyen", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.hoSoNhaTuyenDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("SDT")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("chucVu")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("doanhNghiepId")
                        .HasColumnType("integer");

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("nguoiDungId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("doanhNghiepId");

                    b.HasIndex("nguoiDungId")
                        .IsUnique();

                    b.ToTable("hoSoNhaTuyenDung", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.hoSoUngVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("SDT")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("diaChi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("gioiThieu")
                        .HasColumnType("text");

                    b.Property<string>("gioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("hoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ngaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("nguoiDungId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("nguoiDungId")
                        .IsUnique();

                    b.ToTable("hoSoUngVien", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ketQuaPhanTichCv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("cvUngVienId")
                        .HasColumnType("integer");

                    b.Property<string>("kinhNghiemTrichXuat")
                        .HasColumnType("text");

                    b.Property<string>("kyNangTrichXuat")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ngayPhanTich")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("noiDungTrichXuat")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("cvUngVienId");

                    b.ToTable("ketQuaPhanTichCv", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ketQuaPhuHop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<float>("diemPhuHop")
                        .HasColumnType("real");

                    b.Property<int>("hoSoUngVienId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ngayDanhGia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("phanLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("tinTuyenDungId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("hoSoUngVienId");

                    b.HasIndex("tinTuyenDungId");

                    b.ToTable("ketQuaPhuHop", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.kinhNghiemLamViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsHienTai")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("denNgay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("diaChi")
                        .HasColumnType("text");

                    b.Property<int>("hoSoUngVienId")
                        .HasColumnType("integer");

                    b.Property<string>("moTa")
                        .HasColumnType("text");

                    b.Property<string>("tenCongTy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("tuNgay")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("hoSoUngVienId");

                    b.ToTable("kinhNghiemLamViecs");
                });

            modelBuilder.Entity("Domain.Entities.kyNang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("moTa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("tenKyNang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("tenKyNang")
                        .IsUnique();

                    b.ToTable("kyNang", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.kyNangTinTuyenDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("kyNangId")
                        .HasColumnType("integer");

                    b.Property<string>("mucDoYeuCau")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("tinTuyenDungId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("kyNangId");

                    b.HasIndex("tinTuyenDungId");

                    b.ToTable("kyNangTinTuyenDung", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.kyNangUngVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("hoSoUngVienId")
                        .HasColumnType("integer");

                    b.Property<int>("kyNangId")
                        .HasColumnType("integer");

                    b.Property<float?>("soNamKinhNghiem")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("hoSoUngVienId");

                    b.HasIndex("kyNangId");

                    b.ToTable("kyNangUngVien", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.lichPhongVan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("diaDiem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("donUngTuyenId")
                        .HasColumnType("integer");

                    b.Property<string>("ghiChu")
                        .HasColumnType("text");

                    b.Property<DateTime?>("thoiGianPhongVan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("donUngTuyenId");

                    b.ToTable("lichPhongVan", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.nguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Is_Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("vaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("nguoiDung", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.thongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("Is_Read")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("loaiThongBao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("nguoiDungId")
                        .HasColumnType("integer");

                    b.Property<string>("noiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("nguoiDungId");

                    b.ToTable("thongBao", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.tinTuyenDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("danhMucNgheId")
                        .HasColumnType("integer");

                    b.Property<string>("diaDiemLamViec")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("doanhNghiepId")
                        .HasColumnType("integer");

                    b.Property<string>("kinhNghiemYeuCau")
                        .HasColumnType("text");

                    b.Property<decimal>("luongToiDa")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("luongToiThieu")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("moTaCongViec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ngayHetHan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("quyenLoi")
                        .HasColumnType("text");

                    b.Property<string>("tieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("yeuCauCongViec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("danhMucNgheId");

                    b.HasIndex("doanhNghiepId");

                    b.ToTable("tinTuyenDung", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.cvUngVien", b =>
                {
                    b.HasOne("Domain.Entities.hoSoUngVien", "hoSoUngViens")
                        .WithMany("cvUngViens")
                        .HasForeignKey("hoSoUngVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hoSoUngViens");
                });

            modelBuilder.Entity("Domain.Entities.donUngTuyen", b =>
                {
                    b.HasOne("Domain.Entities.cvUngVien", "cvUngViens")
                        .WithMany()
                        .HasForeignKey("cvUngVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.hoSoUngVien", "hoSoUngViens")
                        .WithMany("donUngTuyens")
                        .HasForeignKey("hoSoUngVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.tinTuyenDung", "tinTuyenDungs")
                        .WithMany("donUngTuyens")
                        .HasForeignKey("tinTuyenDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("cvUngViens");

                    b.Navigation("hoSoUngViens");

                    b.Navigation("tinTuyenDungs");
                });

            modelBuilder.Entity("Domain.Entities.hoSoNhaTuyenDung", b =>
                {
                    b.HasOne("Domain.Entities.doanhNghiep", "doanhNghieps")
                        .WithMany("hoSoNhaTuyenDungs")
                        .HasForeignKey("doanhNghiepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.nguoiDung", "nguoiDungs")
                        .WithOne("hoSoNhaTuyenDungs")
                        .HasForeignKey("Domain.Entities.hoSoNhaTuyenDung", "nguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("doanhNghieps");

                    b.Navigation("nguoiDungs");
                });

            modelBuilder.Entity("Domain.Entities.hoSoUngVien", b =>
                {
                    b.HasOne("Domain.Entities.nguoiDung", "nguoiDungs")
                        .WithOne("hoSoUngViens")
                        .HasForeignKey("Domain.Entities.hoSoUngVien", "nguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nguoiDungs");
                });

            modelBuilder.Entity("Domain.Entities.ketQuaPhanTichCv", b =>
                {
                    b.HasOne("Domain.Entities.cvUngVien", "cvUngViens")
                        .WithMany("ketQuaPhanTichCvs")
                        .HasForeignKey("cvUngVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cvUngViens");
                });

            modelBuilder.Entity("Domain.Entities.ketQuaPhuHop", b =>
                {
                    b.HasOne("Domain.Entities.hoSoUngVien", "hoSoUngViens")
                        .WithMany()
                        .HasForeignKey("hoSoUngVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.tinTuyenDung", "tinTuyenDungs")
                        .WithMany()
                        .HasForeignKey("tinTuyenDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hoSoUngViens");

                    b.Navigation("tinTuyenDungs");
                });

            modelBuilder.Entity("Domain.Entities.kinhNghiemLamViec", b =>
                {
                    b.HasOne("Domain.Entities.hoSoUngVien", "hoSoUngViens")
                        .WithMany()
                        .HasForeignKey("hoSoUngVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hoSoUngViens");
                });

            modelBuilder.Entity("Domain.Entities.kyNangTinTuyenDung", b =>
                {
                    b.HasOne("Domain.Entities.kyNang", "kyNangs")
                        .WithMany("kyNangTinTuyenDungs")
                        .HasForeignKey("kyNangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.tinTuyenDung", "tinTuyenDungs")
                        .WithMany("kyNangTinTuyenDungs")
                        .HasForeignKey("tinTuyenDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("kyNangs");

                    b.Navigation("tinTuyenDungs");
                });

            modelBuilder.Entity("Domain.Entities.kyNangUngVien", b =>
                {
                    b.HasOne("Domain.Entities.hoSoUngVien", "hoSoUngViens")
                        .WithMany("kyNangUngViens")
                        .HasForeignKey("hoSoUngVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.kyNang", "kyNangs")
                        .WithMany("kyNangUngViens")
                        .HasForeignKey("kyNangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("hoSoUngViens");

                    b.Navigation("kyNangs");
                });

            modelBuilder.Entity("Domain.Entities.lichPhongVan", b =>
                {
                    b.HasOne("Domain.Entities.donUngTuyen", "donUngTuyens")
                        .WithMany("lichPhongVans")
                        .HasForeignKey("donUngTuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("donUngTuyens");
                });

            modelBuilder.Entity("Domain.Entities.thongBao", b =>
                {
                    b.HasOne("Domain.Entities.nguoiDung", "nguoiDungs")
                        .WithMany()
                        .HasForeignKey("nguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nguoiDungs");
                });

            modelBuilder.Entity("Domain.Entities.tinTuyenDung", b =>
                {
                    b.HasOne("Domain.Entities.danhMucNghe", "danhMucNghes")
                        .WithMany("tinTuyenDungs")
                        .HasForeignKey("danhMucNgheId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.doanhNghiep", "doanhNghieps")
                        .WithMany("tinTuyenDungs")
                        .HasForeignKey("doanhNghiepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("danhMucNghes");

                    b.Navigation("doanhNghieps");
                });

            modelBuilder.Entity("Domain.Entities.cvUngVien", b =>
                {
                    b.Navigation("ketQuaPhanTichCvs");
                });

            modelBuilder.Entity("Domain.Entities.danhMucNghe", b =>
                {
                    b.Navigation("tinTuyenDungs");
                });

            modelBuilder.Entity("Domain.Entities.doanhNghiep", b =>
                {
                    b.Navigation("hoSoNhaTuyenDungs");

                    b.Navigation("tinTuyenDungs");
                });

            modelBuilder.Entity("Domain.Entities.donUngTuyen", b =>
                {
                    b.Navigation("lichPhongVans");
                });

            modelBuilder.Entity("Domain.Entities.hoSoUngVien", b =>
                {
                    b.Navigation("cvUngViens");

                    b.Navigation("donUngTuyens");

                    b.Navigation("kyNangUngViens");
                });

            modelBuilder.Entity("Domain.Entities.kyNang", b =>
                {
                    b.Navigation("kyNangTinTuyenDungs");

                    b.Navigation("kyNangUngViens");
                });

            modelBuilder.Entity("Domain.Entities.nguoiDung", b =>
                {
                    b.Navigation("hoSoNhaTuyenDungs");

                    b.Navigation("hoSoUngViens");
                });

            modelBuilder.Entity("Domain.Entities.tinTuyenDung", b =>
                {
                    b.Navigation("donUngTuyens");

                    b.Navigation("kyNangTinTuyenDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
