// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CVUngVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("HoSoUngVienId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TrangThaiCV")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HoSoUngVienId");

                    b.ToTable("CVUngVien", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DanhGia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DonUngTuyenId")
                        .HasColumnType("integer");

                    b.Property<string>("KetLuan")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayPhanHoi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDungPhanHoi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DonUngTuyenId");

                    b.ToTable("DanhGia", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DanhMucNghe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TenNghe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("TenNghe")
                        .IsUnique();

                    b.ToTable("DanhMucNghe", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DoanhNghiep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("LinhVucHoatDong")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("QuyMoNhanSu")
                        .HasColumnType("text");

                    b.Property<string>("TenDoanhNghiep")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Website")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("DoanhNghiep", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.DonUngTuyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CVUngVienId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int>("HoSoUngVienId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayUngTuyen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NguoiXuLyId")
                        .HasColumnType("integer");

                    b.Property<int>("TinTuyenDungId")
                        .HasColumnType("integer");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CVUngVienId");

                    b.HasIndex("HoSoUngVienId");

                    b.HasIndex("TinTuyenDungId");

                    b.ToTable("DonUngTuyen", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HoSoNhaTuyenDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DoanhNghiepId")
                        .HasColumnType("integer");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("integer");

                    b.Property<string>("SDT")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DoanhNghiepId");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("HoSoNhaTuyenDung", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HoSoUngVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GioiThieu")
                        .HasColumnType("text");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsTimViec")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<double>("MucLuongMongMuon")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("integer");

                    b.Property<string>("SDT")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ViTriUngTuyen")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("HoSoUngVien", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KetQuaPhanTichCv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CVUngVienId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("HocVanTrichXuat")
                        .HasColumnType("text");

                    b.Property<string>("KinhNghiemTrichXuat")
                        .HasColumnType("text");

                    b.Property<string>("KyNangTrichXuat")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("NoiDungTrichXuat")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CVUngVienId");

                    b.ToTable("KetQuaPhanTichCv", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KetQuaPhuHop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<float>("DiemPhuHop")
                        .HasColumnType("real");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int>("HoSoUngVienId")
                        .HasColumnType("integer");

                    b.Property<int?>("HoSoUngVienId1")
                        .HasColumnType("integer");

                    b.Property<string>("KyNangThieu")
                        .HasColumnType("text");

                    b.Property<string>("KyNangThoa")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("PhanLoai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TinTuyenDungId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HoSoUngVienId");

                    b.HasIndex("HoSoUngVienId1");

                    b.HasIndex("TinTuyenDungId");

                    b.ToTable("KetQuaPhuHop", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KinhNghiemLamViec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DenNgay")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("HoSoUngVienId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsHienTai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("TuNgay")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("HoSoUngVienId");

                    b.ToTable("KinhNghiemLamViec", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KyNang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TenKyNang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("TenKyNang")
                        .IsUnique();

                    b.ToTable("KyNang", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KyNangTinTuyenDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("KyNangId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("MucDoYeuCau")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<int>("TinTuyenDungId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KyNangId");

                    b.HasIndex("TinTuyenDungId");

                    b.ToTable("KyNangTinTuyenDung", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KyNangUngVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("HoSoUngVienId")
                        .HasColumnType("integer");

                    b.Property<int>("KyNangId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<int>("MucDoThongThao")
                        .HasColumnType("integer");

                    b.Property<float?>("SoNamKinhNghiem")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("HoSoUngVienId");

                    b.HasIndex("KyNangId");

                    b.ToTable("KyNangUngVien", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LichPhongVan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DiaDiem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("DonUngTuyenId")
                        .HasColumnType("integer");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<int>("HinhThuc")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ThoiGianPhongVan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DonUngTuyenId");

                    b.ToTable("LichPhongVan", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.LoiMoiNhanSu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DoanhNghiepId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("LoiMoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("NgayHetHan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NguoiDaiDienId")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("DoanhNghiepId");

                    b.HasIndex("NguoiDaiDienId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("LoiMoiNhanSu", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<string>("LoaiThongBao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("integer");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TinTuyenDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("DanhMucNgheId")
                        .HasColumnType("integer");

                    b.Property<string>("DiaDiemLamViec")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("DoanhNghiepId")
                        .HasColumnType("integer");

                    b.Property<string>("KinhNghiemYeuCau")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text");

                    b.Property<decimal>("LuongToiDa")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("LuongToiThieu")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("MoTaCongViec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NguoiDangTinId")
                        .HasColumnType("integer");

                    b.Property<string>("QuyenLoi")
                        .HasColumnType("text");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("YeuCauCongViec")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DanhMucNgheId");

                    b.HasIndex("DoanhNghiepId");

                    b.HasIndex("NguoiDangTinId");

                    b.ToTable("TinTuyenDung", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CVUngVien", b =>
                {
                    b.HasOne("Domain.Entities.HoSoUngVien", "HoSoUngVien")
                        .WithMany("CVUngViens")
                        .HasForeignKey("HoSoUngVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoUngVien");
                });

            modelBuilder.Entity("Domain.Entities.DanhGia", b =>
                {
                    b.HasOne("Domain.Entities.DonUngTuyen", "DonUngTuyen")
                        .WithMany("DanhGias")
                        .HasForeignKey("DonUngTuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonUngTuyen");
                });

            modelBuilder.Entity("Domain.Entities.DonUngTuyen", b =>
                {
                    b.HasOne("Domain.Entities.CVUngVien", "CVUngVien")
                        .WithMany()
                        .HasForeignKey("CVUngVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.HoSoUngVien", "HoSoUngVien")
                        .WithMany("DonUngTuyens")
                        .HasForeignKey("HoSoUngVienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TinTuyenDung", "TinTuyenDung")
                        .WithMany("DonUngTuyens")
                        .HasForeignKey("TinTuyenDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CVUngVien");

                    b.Navigation("HoSoUngVien");

                    b.Navigation("TinTuyenDung");
                });

            modelBuilder.Entity("Domain.Entities.HoSoNhaTuyenDung", b =>
                {
                    b.HasOne("Domain.Entities.DoanhNghiep", "DoanhNghiep")
                        .WithMany("HoSoNhaTuyenDungs")
                        .HasForeignKey("DoanhNghiepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.NguoiDung", "NguoiDung")
                        .WithOne("HoSoNhaTuyenDung")
                        .HasForeignKey("Domain.Entities.HoSoNhaTuyenDung", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoanhNghiep");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Domain.Entities.HoSoUngVien", b =>
                {
                    b.HasOne("Domain.Entities.NguoiDung", "NguoiDung")
                        .WithOne("HoSoUngVien")
                        .HasForeignKey("Domain.Entities.HoSoUngVien", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Domain.Entities.KetQuaPhanTichCv", b =>
                {
                    b.HasOne("Domain.Entities.CVUngVien", "CVUngVien")
                        .WithMany("KetQuaPhanTichCvs")
                        .HasForeignKey("CVUngVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CVUngVien");
                });

            modelBuilder.Entity("Domain.Entities.KetQuaPhuHop", b =>
                {
                    b.HasOne("Domain.Entities.HoSoUngVien", "HoSoUngVien")
                        .WithMany()
                        .HasForeignKey("HoSoUngVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.HoSoUngVien", null)
                        .WithMany("KetQuaPhuHops")
                        .HasForeignKey("HoSoUngVienId1");

                    b.HasOne("Domain.Entities.TinTuyenDung", "TinTuyenDung")
                        .WithMany()
                        .HasForeignKey("TinTuyenDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoUngVien");

                    b.Navigation("TinTuyenDung");
                });

            modelBuilder.Entity("Domain.Entities.KinhNghiemLamViec", b =>
                {
                    b.HasOne("Domain.Entities.HoSoUngVien", "HoSoUngVien")
                        .WithMany("KinhNghiemLamViecs")
                        .HasForeignKey("HoSoUngVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoUngVien");
                });

            modelBuilder.Entity("Domain.Entities.KyNangTinTuyenDung", b =>
                {
                    b.HasOne("Domain.Entities.KyNang", "KyNang")
                        .WithMany("KyNangTinTuyenDungs")
                        .HasForeignKey("KyNangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TinTuyenDung", "TinTuyenDung")
                        .WithMany("KyNangTinTuyenDungs")
                        .HasForeignKey("TinTuyenDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KyNang");

                    b.Navigation("TinTuyenDung");
                });

            modelBuilder.Entity("Domain.Entities.KyNangUngVien", b =>
                {
                    b.HasOne("Domain.Entities.HoSoUngVien", "HoSoUngVien")
                        .WithMany("KyNangUngViens")
                        .HasForeignKey("HoSoUngVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.KyNang", "KyNang")
                        .WithMany("KyNangUngViens")
                        .HasForeignKey("KyNangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoSoUngVien");

                    b.Navigation("KyNang");
                });

            modelBuilder.Entity("Domain.Entities.LichPhongVan", b =>
                {
                    b.HasOne("Domain.Entities.DonUngTuyen", "DonUngTuyen")
                        .WithMany("LichPhongVans")
                        .HasForeignKey("DonUngTuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonUngTuyen");
                });

            modelBuilder.Entity("Domain.Entities.LoiMoiNhanSu", b =>
                {
                    b.HasOne("Domain.Entities.DoanhNghiep", "DoanhNghiep")
                        .WithMany("LoiMoiNhanSus")
                        .HasForeignKey("DoanhNghiepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.NguoiDung", "NguoiDaiDien")
                        .WithMany("LoiMoiNhanSus")
                        .HasForeignKey("NguoiDaiDienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DoanhNghiep");

                    b.Navigation("NguoiDaiDien");
                });

            modelBuilder.Entity("Domain.Entities.ThongBao", b =>
                {
                    b.HasOne("Domain.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Domain.Entities.TinTuyenDung", b =>
                {
                    b.HasOne("Domain.Entities.DanhMucNghe", "DanhMucNghe")
                        .WithMany("TinTuyenDungs")
                        .HasForeignKey("DanhMucNgheId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.DoanhNghiep", "DoanhNghiep")
                        .WithMany("TinTuyenDungs")
                        .HasForeignKey("DoanhNghiepId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.NguoiDung", "NguoiDangTin")
                        .WithMany("TinTuyenDungs")
                        .HasForeignKey("NguoiDangTinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMucNghe");

                    b.Navigation("DoanhNghiep");

                    b.Navigation("NguoiDangTin");
                });

            modelBuilder.Entity("Domain.Entities.CVUngVien", b =>
                {
                    b.Navigation("KetQuaPhanTichCvs");
                });

            modelBuilder.Entity("Domain.Entities.DanhMucNghe", b =>
                {
                    b.Navigation("TinTuyenDungs");
                });

            modelBuilder.Entity("Domain.Entities.DoanhNghiep", b =>
                {
                    b.Navigation("HoSoNhaTuyenDungs");

                    b.Navigation("LoiMoiNhanSus");

                    b.Navigation("TinTuyenDungs");
                });

            modelBuilder.Entity("Domain.Entities.DonUngTuyen", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("LichPhongVans");
                });

            modelBuilder.Entity("Domain.Entities.HoSoUngVien", b =>
                {
                    b.Navigation("CVUngViens");

                    b.Navigation("DonUngTuyens");

                    b.Navigation("KetQuaPhuHops");

                    b.Navigation("KinhNghiemLamViecs");

                    b.Navigation("KyNangUngViens");
                });

            modelBuilder.Entity("Domain.Entities.KyNang", b =>
                {
                    b.Navigation("KyNangTinTuyenDungs");

                    b.Navigation("KyNangUngViens");
                });

            modelBuilder.Entity("Domain.Entities.NguoiDung", b =>
                {
                    b.Navigation("HoSoNhaTuyenDung");

                    b.Navigation("HoSoUngVien");

                    b.Navigation("LoiMoiNhanSus");

                    b.Navigation("TinTuyenDungs");
                });

            modelBuilder.Entity("Domain.Entities.TinTuyenDung", b =>
                {
                    b.Navigation("DonUngTuyens");

                    b.Navigation("KyNangTinTuyenDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
